package com.flux.deploy.cli;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * schema 子命令：向 stdout 输出 JSON Schema，供 AI Skill 实时加载以了解当前 CLI 能力。
 *
 * <p>输出格式与 {@code references/cli-config-schema.md} 保持一致，CLI 是唯一事实来源。</p>
 *
 * @author xumanyi
 * @date 2026-03-21
 */
final class SchemaCommand {

    static final String CLI_VERSION = "1.1.2";

    private SchemaCommand() {
    }

    /**
     * 执行 schema 子命令，输出 JSON Schema 到 stdout
     *
     * @return 退出码 0
     * @author xumanyi
     * @date 2026-03-21
     */
    static int run() {
        Gson gson = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
        System.out.println(gson.toJson(buildSchema()));
        return 0;
    }

    // -------------------------------------------------------------------------
    // Schema 构建
    // -------------------------------------------------------------------------

    /**
     * 构建完整的 JSON Schema 根对象
     *
     * @return Schema 根对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildSchema() {
        Map<String, Object> root = ordered();
        root.put("$schema", "http://json-schema.org/draft-07/schema#");
        root.put("$id", "flux-deploy-cli-config");
        root.put("cliVersion", CLI_VERSION);
        root.put("description",
                "flux-deploy-cli deploy subcommand config schema. " +
                "Authoritative source for all config fields. " +
                "Generated by: java -jar flux-deploy-cli.jar schema");
        root.put("type", "object");
        root.put("required", Arrays.asList("ftp", "remoteDir"));
        root.put("properties", buildProperties());
        root.put("exitCodes", buildExitCodes());
        return root;
    }

    /**
     * 构建顶层 properties 对象
     *
     * @return properties 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildProperties() {
        Map<String, Object> props = ordered();
        props.put("ftp", buildFtp());
        props.put("remoteDir", prop("string",
                "Remote working directory to cwd into after login. E.g. /开发/AISKILL测试项目/TMS V9.0-P7/"));
        props.put("mode", propEnum(new String[]{"full", "incremental"}, "full",
                "Update mode. " +
                "full = upload whole localFile, CLI does NOT compile (default). " +
                "incremental = caller supplies files list, CLI ALWAYS runs mvn package, then patches the remote package. " +
                "Caller (plugin UI / Skill) is responsible for producing the files list — manually or via git status. " +
                "CLI no longer auto-detects changes."));
        props.put("projectDir", prop("string",
                "Absolute path to Maven module root (containing pom.xml). " +
                "Required for incremental mode; ignored in full mode. " +
                "Used as mvn working directory."));
        props.put("files", buildFilesArray());
        props.put("mavenHome", prop("string",
                "Optional: MAVEN_HOME override. Lookup order: this > mvnw > MAVEN_HOME env > shell which mvn."));
        props.put("javaHome", prop("string",
                "Optional: JAVA_HOME for the mvn subprocess. Defaults to inherited process environment."));
        props.put("targets", buildTargets());
        props.put("meta", buildMeta());
        props.put("options", buildOptions());
        props.put("jarArtifactId", prop("string",
                "ArtifactId prefix used to match the old jar inside a war's WEB-INF/lib. " +
                "E.g. tmsv6-tm10-srv matches tmsv6-tm10-srv-9.0.0-SNAPSHOT.jar inside the war."));
        props.put("embedTargets", buildEmbedTargets());
        return props;
    }

    /**
     * 构建 files 字段的数组类型描述
     *
     * @return files 字段 Schema 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildFilesArray() {
        Map<String, Object> m = ordered();
        m.put("type", "array");
        m.put("description",
                "REQUIRED for mode=incremental. Changed source file paths relative to projectDir, " +
                "optionally with git status prefix (e.g. \"M src/main/java/Foo.java\", \"D src/main/resources/bar.xml\"). " +
                "List source: caller decides — plugin UI's prefilled-checkbox component, or Skill running git status " +
                "and confirming with user. CLI does not auto-detect.");
        Map<String, Object> item = ordered();
        item.put("type", "string");
        m.put("items", item);
        return m;
    }

    /**
     * 构建 ftp 字段的对象类型描述
     *
     * @return ftp 字段 Schema 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildFtp() {
        Map<String, Object> ftp = ordered();
        ftp.put("type", "object");
        ftp.put("required", Arrays.asList("host", "username"));

        Map<String, Object> ftpProps = ordered();
        ftpProps.put("host", prop("string",
                "FTP host IP or hostname. No ftp:// prefix."));
        ftpProps.put("port", propWithDefault("integer", 18080,
                "FTP port."));
        ftpProps.put("username", prop("string",
                "Login username. Also used as credential cache match key."));
        ftpProps.put("password", prop("string",
                "Not recommended. Password resolution priority: --password-file > ftp.password > credential cache " +
                "(~/.flux-deploy/credentials.toml). Skill should leave this empty and rely on the credential cache managed by `credential` subcommand."));
        ftp.put("properties", ftpProps);
        return ftp;
    }

    /**
     * 构建 targets 字段的数组类型描述
     *
     * @return targets 字段 Schema 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildTargets() {
        Map<String, Object> targets = ordered();
        targets.put("type", "array");
        targets.put("description",
                "List of packages to deploy. At least one of targets or embedTargets must be present.");

        Map<String, Object> itemProps = ordered();
        itemProps.put("localFile", prop("string",
                "Absolute local path to compiled jar/war. Required for mode=full. " +
                "For mode=incremental leave empty — CLI populates it after building the staging package."));
        itemProps.put("name", prop("string",
                "Remote filename to match on FTP. " +
                "full mode: if omitted, CLI recursively scans remoteDir for files whose basename " +
                "matches localFile's basename and updates all matches. " +
                "incremental mode: REQUIRED (StagingPackageBuilder needs it to locate the remote package to patch)."));
        itemProps.put("relativePath", prop("string",
                "Relative path of the file under remoteDir. " +
                "Required when the file is in a subdirectory. Leave empty if directly under remoteDir."));

        Map<String, Object> item = ordered();
        item.put("type", "object");
        item.put("required", Arrays.asList("localFile"));
        item.put("properties", itemProps);
        targets.put("items", item);
        return targets;
    }

    /**
     * 构建 meta 字段的对象类型描述
     *
     * @return meta 字段 Schema 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildMeta() {
        Map<String, Object> meta = ordered();
        meta.put("type", "object");
        meta.put("description",
                "Task metadata for version note. Omit entirely when options.skipNote=true.");

        Map<String, Object> metaProps = ordered();
        metaProps.put("taskId", prop("string",
                "Task ID appended to *_update_notes.txt."));
        metaProps.put("customerId", prop("string",
                "Customer service ID."));
        metaProps.put("operator", prop("string",
                "Operator English ID. REQUIRED when options.skipBackup=false. " +
                "Used to name backup dir: <YYYYMMDD>_<operator>."));
        metaProps.put("backupDirName", prop("string",
                "Explicit backup dir name. Overrides auto-generated <YYYYMMDD>_<operator>. " +
                "Leave empty in normal cases."));
        meta.put("properties", metaProps);
        return meta;
    }

    /**
     * 构建 options 字段的对象类型描述
     *
     * @return options 字段 Schema 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildOptions() {
        Map<String, Object> options = ordered();
        options.put("type", "object");

        Map<String, Object> optProps = ordered();
        optProps.put("dryRun", propWithDefault("boolean", false,
                "Preview only: check remote file existence, stale locks, local file size. No remote changes."));
        optProps.put("skipBackup", propWithDefaultAndNote("boolean", false,
                "Skip BackupGate (no backup). CLI default is false (backup enabled). " +
                "Skill sets true unless user explicitly requests backup."));
        optProps.put("skipLock", propWithDefault("boolean", false,
                "Skip PreCheck/Lock/Unlock gates. Only when an external lock is already held."));
        optProps.put("skipNote", propWithDefaultAndNote("boolean", false,
                "Skip note append (no version record). CLI default is false (note enabled). " +
                "Skill sets true unless taskId/customerId are provided."));
        optProps.put("outputFormat", propEnum(
                new String[]{"json", "text"}, "text",
                "Output format. Skill always passes json for machine-readable result parsing."));
        options.put("properties", optProps);
        return options;
    }

    /**
     * 构建 embedTargets 字段的数组类型描述
     *
     * @return embedTargets 字段 Schema 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildEmbedTargets() {
        Map<String, Object> embed = ordered();
        embed.put("type", "array");
        embed.put("description",
                "WAR embed targets. Used when local artifact is a jar and must replace " +
                "the same-named jar inside war WEB-INF/lib. Requires jarArtifactId.");

        Map<String, Object> itemProps = ordered();
        itemProps.put("warName", prop("string",
                "Target war filename. E.g. tm10srv.war"));
        itemProps.put("warRelativePath", prop("string",
                "Relative path of the war under remoteDir. Leave empty if directly under remoteDir."));

        Map<String, Object> item = ordered();
        item.put("type", "object");
        item.put("required", Arrays.asList("warName"));
        item.put("properties", itemProps);
        embed.put("items", item);
        return embed;
    }

    /**
     * 构建退出码说明对象
     *
     * @return exitCodes 对象
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> buildExitCodes() {
        Map<String, Object> codes = ordered();
        codes.put("0",
                "All targets succeeded. Parse stdout JSON for per-target " +
                "backupPath/localSha256/remoteSha256/verified/noteUpdated.");
        codes.put("64",
                "Usage/config error: bad JSON syntax, missing required field, local file not found, " +
                "password unavailable (neither --password-file/ftp.password/credential cache), unknown flag. " +
                "Show CLI stderr first line to user and fix before retry. " +
                "If stderr contains '缺少密码' or 'Tag mismatch' -> prompt user to run `credential set`.");
        codes.put("70",
                "Runtime error: FTP connect failed, remote verify failed, gate error. " +
                "CLI has auto-rolled back. Parse rollback field and report. " +
                "Ask user if manual FTP cleanup is needed.");
        return codes;
    }

    // -------------------------------------------------------------------------
    // 辅助构建方法
    // -------------------------------------------------------------------------

    /**
     * 构建基础属性描述对象（type + description）
     *
     * @param type        JSON Schema 类型字符串
     * @param description 属性描述
     * @return 属性描述 Map
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> prop(String type, String description) {
        Map<String, Object> m = ordered();
        m.put("type", type);
        m.put("description", description);
        return m;
    }

    /**
     * 构建带默认值的属性描述对象（type + default + description）
     *
     * @param type        JSON Schema 类型字符串
     * @param defaultVal  属性默认值
     * @param description 属性描述
     * @return 属性描述 Map
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> propWithDefault(String type, Object defaultVal, String description) {
        Map<String, Object> m = ordered();
        m.put("type", type);
        m.put("default", defaultVal);
        m.put("description", description);
        return m;
    }

    /**
     * 构建带默认值和额外说明的属性描述对象，同 {@link #propWithDefault}
     *
     * @param type        JSON Schema 类型字符串
     * @param defaultVal  属性默认值
     * @param description 属性描述
     * @return 属性描述 Map
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> propWithDefaultAndNote(String type, Object defaultVal, String description) {
        return propWithDefault(type, defaultVal, description);
    }

    /**
     * 构建枚举类型属性描述对象（type=string + enum + default + description）
     *
     * @param values      枚举值数组
     * @param defaultVal  默认枚举值
     * @param description 属性描述
     * @return 属性描述 Map
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> propEnum(String[] values, Object defaultVal, String description) {
        Map<String, Object> m = ordered();
        m.put("type", "string");
        m.put("enum", Arrays.asList(values));
        m.put("default", defaultVal);
        m.put("description", description);
        return m;
    }

    /**
     * 创建保持插入顺序的 LinkedHashMap
     *
     * @return 空的 LinkedHashMap 实例
     * @author xumanyi
     * @date 2026-03-21
     */
    private static Map<String, Object> ordered() {
        return new LinkedHashMap<>();
    }
}
